### PR TITLE
gofmt -s

### PR DESCRIPTION
**Pull request by shawnps**

### CODE REVIEW

**Comment by shirou** [comment]
Thanks!

**Comment by shawnps** [comment]
@shirou have you seen this error before? I can't `go get`:

```
../../../github.com/shirou/w32/advapi32.go:15: undefined: syscall.NewLazyDLL
../../../github.com/shirou/w32/comctl32.go:13: undefined: syscall.NewLazyDLL
../../../github.com/shirou/w32/comdlg32.go:13: undefined: syscall.NewLazyDLL
../../../github.com/shirou/w32/dwmapi.go:21: undefined: syscall.NewLazyDLL
../../../github.com/shirou/w32/gdi32.go:13: undefined: syscall.NewLazyDLL
../../../github.com/shirou/w32/gdiplus.go:92: undefined: syscall.NewLazyDLL
../../../github.com/shirou/w32/kernel32.go:13: undefined: syscall.NewLazyDLL
../../../github.com/shirou/w32/ole32.go:13: undefined: syscall.NewLazyDLL
../../../github.com/shirou/w32/oleaut32.go:13: undefined: syscall.NewLazyDLL
../../../github.com/shirou/w32/opengl32.go:13: undefined: syscall.NewLazyDLL
../../../github.com/shirou/w32/opengl32.go:13: too many errors
```

I'm using Go version 1.5.3

**Comment by shawnps** [comment]
Hmm seems related https://github.com/go-ole/go-ole/issues/47

Because I'm on a Mac I guess

**Comment by shirou** [comment]
if go get on my Mac, same error occurred. Could you test on your Windows environment?

**Comment by shawnps** [comment]
@shirou sorry, I'm not using it on windows. This lib is imported by your `gopsutil` tool which I do use

**Comment by shirou** [comment]
w32 is imported from `gopsutil/process/process_windows.go` only. This file has `// +build windows` build option, so `go get  github.com/shirou/w32` is not invoked on your Mac environment, I think.

For example, go under gopsutil/process and type `go get -u`, there are no error on my Mac environment. Do you set GOOS environment to windows or use some other build tool?

**Comment by shawnps** [comment]
@shirou ah I see... You're right, if I go get `gopsutil` it's fine. Sorry

**Pull request merged**
